### PR TITLE
Simplify fit-text directive

### LINKED ISSUE #1190: bug: text area resizing needs some work
**Describe the bug**
The current text area resizing needs some work.  I (Chris) have actually worked on this for nearly 8 hours and still have yet to achieve something that implements all the requirements.  The current implementation on staging also utilizes extra JS/CSS that is probably not necessary.

**Expected behavior**

1) The text area defaults to a single line width when there is either no content or a single line of content
2) Switching between entries should appropriately size the text area to it's content
3) Resizing the window should trigger a text area resize
4) Enter text that results in additional lines should grow the text area appropriately
5) Deleting text that results in fewer lines should shrink the text area appropriately

The current code implements number 4 completely (auto-grow) but has significant issues with numbers 1,2,3 and 5, with the shrink effect only reducing the size by 1px for each key-up or window resize event.  This has the effect of the text area slowly approaching the correct size.

Video showing partial implementation currently shipped on v1.9
https://user-images.githubusercontent.com/3444521/135624012-8c70a2bc-44da-4b0d-8630-9f6136079915.mp4

### PR DESCRIPTION
**Pull request by megahirt**
## Description

This removes some unnecessary complexity in the fit-text directive while completing required features of the text area resize issue #1190

This PR also optimizes a few different container height and margin values to provide a more consistent app height across viewports.  This complements the fit-text directive changes, which previously were making changes to parent containers via JS/CSS.

The change to dc-rendered now puts a maximum of two lines on the div across all viewports.

Fixes #1190 and #1172

### Type of Change

- Bug fix (non-breaking change which fixes an issue)

## Video demo

You can watch the old behavior in #1190 here:
https://user-images.githubusercontent.com/3444521/135624012-8c70a2bc-44da-4b0d-8630-9f6136079915.mp4

See below for the new behavior:
https://user-images.githubusercontent.com/3444521/135638562-e92470aa-4c74-450a-a6be-d29deaf44977.mp4

## How Has This Been Tested?

- [ ] The text area defaults to a single line width when there is either no content or a single line of content
- [ ] Switching between entries should appropriately size the text area to it's content
- [ ] Resizing the window / switching viewports should trigger a text area resize
- [ ] Enter text that results in additional lines should grow the text area appropriately
- [ ] Deleting text that results in fewer lines should shrink the text area appropriately

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have reviewed the title/description of this PR which will be used as the squashed PR commit message
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: src/angular-app/languageforge/lexicon/shared/fit-text.directive.ts [hunk 1]
```diff
@@ -3,52 +3,34 @@ import * as angular from 'angular';
...
-      var primaryNavigationElement = angular.element(document).find('#primary-navigation');
-      var primaryNavigationHeight = primaryNavigationElement.height();
-      var scrollingEditorContainerElement = angular.element(document).find('#scrolling-editor-container');
-
-      var adjHeight = wHeight - (tHeight - defaultHeight);
-      var sHeight = adjHeight - (177 + primaryNavigationHeight);
-      var lHeight = adjHeight - (447 + primaryNavigationHeight);
-      scrollingEditorContainerElement.css({ height: sHeight + 'px' });
+        // grow to the height necessary to fit all the text
+        el.style.height = el.scrollHeight+"px";
```
Comment (longrunningprocess) [inline src/angular-app/languageforge/lexicon/shared/fit-text.directive.ts:17]: very slick there!

File: src/angular-app/languageforge/lexicon/shared/fit-text.directive.ts [hunk 2]
```diff
@@ -3,52 +3,34 @@ import * as angular from 'angular';
...
       updateHeight();
     });
 
+    // this is required in order to resize the text area when switching between entries
     scope.$watch(() => {
-      if (!kInput){
-        kInput = false;
-        updateHeight();
-      }
+      updateHeight();
```
Comment (longrunningprocess) [inline src/angular-app/languageforge/lexicon/shared/fit-text.directive.ts:32]: bonus points for eliminating the `if` 🏅

**Review by longrunningprocess — APPROVED** [review]
I'm so impressed, your solution is elegant and your code looks great!

**Comment by longrunningprocess** [comment]
unit tests failed, I'm kicking it off again in case it was a flaky failure, otherwise I'll dig into it.

**Comment by longrunningprocess** [comment]
aight gtg, I'm going to go ahead and merge this for @megahirt based on my understanding from our Slack conversations.
