### PR TITLE
Hide Share button from My Projects Page

### LINKED ISSUE #1241: Remove "Share" button from My Projects Page
**Describe the bug**
Currently, the "Share" button is visible on the My Projects page. But when you click on it, it opens a window with just a heading. It doesn't do anything. It should be removed. 

**To Reproduce**
1. Go to https://languageforge.org/app/projects from an account with sharing permissions
2. Click on "Share"
3. Observe that there is nothing to do. 

**Expected behavior**
No "Share" button on the "My Projects" page. The button should only be visible while working in a given project. 

**Screenshots**
image
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Mobile (please complete the following information):**
NA
**Android App in Google Play**
NA

**Additional context**
None

### PR DESCRIPTION
**Pull request by palmtreefrb**
## Description

Hide Share button from My Projects and other non lexicon project pages. 

Fixes #1241 

### Type of Change

- New feature (non-breaking change which adds functionality)
- UI change

## Screenshots
Screenshot from 2022-01-17 15-38-12
Screenshot from 2022-01-17 15-38-48
Screenshot from 2022-01-17 15-39-37

Please provide screenshots / animations for any change that involves the UI.  Please provide animations to demonstrate user interaction / behavior changes

## Testing on your branch

Please describe how to test and/or verify your changes. Provide instructions so we can reproduce.  Please also provide relevant test data as necessary.  These instructions will be used for QA testing below.

- [ ] Navigate to a non-lexicon project page 
- [ ] Navigate to a lexicon project page

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have reviewed the title/description of this PR which will be used as the squashed PR commit message

## qa.languageforge.org testing

Reviewers: add/replace your name below and check the box to sign-off/attest the feature works as expected on qa.languageforge.org

- [ ] Reviewer1 (YYYY-MM-DD HH:MM)
- [ ] Reviewer2 (YYYY-MM-DD HH:MM)

### CODE REVIEW

File: src/angular-app/bellows/core/navbar.controller.ts [hunk 1]
```diff
@@ -24,15 +24,21 @@ export class NavbarController implements angular.IController {
   displayShareButton: boolean;
   projectTypeNames: ProjectTypeNames;
   siteName: string;
+  showShareButton: boolean = false;
```
Comment (megahirt) [inline src/angular-app/bellows/core/navbar.controller.ts:27]: How about we change the variable name to `isLexiconProject` and then use that variable to show/hide the settings button as well?  Right now the settings button uses a `ng-if="$ctrl.project"` which could be changed to `ng-if="isLexiconProject"`

**Review by megahirt — CHANGES_REQUESTED** [review]
The code looks good, and it should work as is, I'd like to ask you to make the settings and share button visibility logic the same, since they should be the same.  See my comment about renaming the variable.  Thank you!

File: src/angular-app/bellows/core/navbar.controller.ts [hunk 2]
```diff
@@ -24,15 +24,21 @@ export class NavbarController implements angular.IController {
   displayShareButton: boolean;
```
[the remark this answers is not in the document]
Comment (palmtreefrb) [reply src/angular-app/bellows/core/navbar.controller.ts]: This help me to discover additional business logic that I have now implemented.

**Comment by palmtreefrb** [comment]
Added additional business logic around displaying the header buttons.

**Review by josephmyers — APPROVED** [review]

File: src/Site/views/languageforge/container/languageforge.html.twig [hunk 3]
```diff
@@ -81,7 +81,7 @@
                     <breadcrumbs id="top" class="breadcrumbs d-none d-md-block"></breadcrumbs>
                 </div>
                 <ul class="nav navbar-nav">
-                    <li class="nav-item" ng-if="$ctrl.project" id="settings-dropdown-button" uib-dropdown data-ng-class="{'app-settings-available': $ctrl.header.settings.length > 0 && $ctrl.currentUserIsProjectManager}">
+                    <li class="nav-item" ng-if="$ctrl.isLexiconProject" id="settings-dropdown-button" uib-dropdown data-ng-class="{'app-settings-available': $ctrl.header.settings.length > 0 && $ctrl.currentUserIsProjectManager}">
```
Comment (megahirt) [inline src/Site/views/languageforge/container/languageforge.html.twig:84]: I see how you tried to combine the "show/hide" into a single boolean `isLexiconProject` but this won't work here since you have conflated the logic of the share button into the isLexiconProject boolean.

I think what we really need is a displayShareButton and displaySettingsButton whose logic contains the right combination of switches.  I know that the logic is a bit fuzzy and not entirely clear from the PR.

**Review by megahirt — CHANGES_REQUESTED** [review]
I recommend that have two clear booleans (or methods) that are defined in the controller, and simply reference them in the template.

**Review by megahirt — APPROVED** [review]

File: src/Site/views/languageforge/container/languageforge.html.twig (hunk 3 above)
Comment (megahirt) [reply src/Site/views/languageforge/container/languageforge.html.twig]: I have fixed this up to my own satisfaction, so I will merge when tests are passing.

**Comment by megahirt** [comment]
I have rebased this branch onto the latest commit where e2e tests were still working.  My hope is that I can leverage that commit for a bit longer on these strategic PRs.

**Comment by megahirt** [comment]
Actually, my latest changes don't work, and I've run out of time to figure out why, so I'm going to leave this PR for now.  Will pick it up again sometime soon.

**Review by megahirt — CHANGES_REQUESTED** [review]
Needs more work - still in progress

**Comment by longrunningprocess** [comment]
https://github.com/sillsdev/LfMerge/pull/142

**Comment by megahirt** [comment]
I have finally turned my attention back to this and was able to finish testing on my branch.

- [ ] <kbd>Share</kbd> and <kbd>Settings</kbd> buttons are not visible on any page other than the editor page
- [ ] <kbd>Settings</kbd> button is only visible in editor view.  Only visible by the manager
- [ ] When "allow others to share" is checked, all project members can see the <kbd>Share</kbd> button
- [ ] When "allow others to share" is NOT checked, only the manager / owner can see the <kbd>Share</kbd> button

In addition, all the E2E tests are passing on my local development machine.

**Comment by palmtreefrb** [comment]
These two test failed. The buttons are still available on the "List", "Project Settings", "Synchronize", "Import Data" and "Configuration" pages.
- [ ] <kbd>Share</kbd> and <kbd>Settings</kbd> buttons are not visible on any page other than the editor page
- [ ] <kbd>Settings</kbd> button is only visible in editor view.  Only visible by the manager

**Comment by alex-larkin** [comment]
Great work Rick and everyone! Just to clarify, is this still behind worked on? I did observe some of the behaviors being mentioned. Thanks.
