### PR TITLE
eliminate notifications for offline/online status

### LINKED ISSUE #1571: bug: online/offline messages are distracting and unnecessary for flaky connections that mostly work
**Describe the bug**
A user has reported that the online/offline messages fill their screen when they are trying to use Language Forge.  This could be due to a flaky/unstable internet connection.  The user reports that the website is still usable, but that the messages continue to fill the screen if she doesn't continually close them.

**To Reproduce**

I don't think we can repro this behavior easily.

**Expected behavior**
We don't need explicit messages for online/offline that repeat themselves.  We just need a simple indicator for online/offline.  We already have this with the change in title and color.

**Screenshots**
Screenshot (8)
User-reported screenshot

Proposed change:

- Remove use of the notice system for online/offline transitions.

The existing color change and title change to "Language Forge Offline" is enough for the user to notice.
See screenshot:
image

### PR DESCRIPTION
**Pull request by longrunningprocess**
Fixes #1571 

## Description

This PR seeks to quiet down the LF notification system when detecting online/offline status.

### Type of Change

Only keep lines below that describe this change, then delete the rest.

- Bug fix (non-breaking change which fixes an issue)

## Screenshots

Without the notifications:

https://user-images.githubusercontent.com/4412848/199065248-c961cd81-b506-46e1-b8b5-3975da0c94bf.mov

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the title/description of this PR which will be used as the squashed PR commit message
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works

## How to test

- Go offline (via your wifi or dev tools->Network->Offline) and ensure the top app bar changes colors and the header title shows "Offline"

## qa.languageforge.org testing

Testers should add his/her findings to end of the PR in a comment and include screenshots, files, etc that are beneficial.

### CODE REVIEW

**Comment by longrunningprocess** [comment]
If we don't want to go quickly with this, I can also add commits for whatever a final solution might look like including the removal of the https://github.com/hubspot/offline dep as well as migration to the modern approach:  https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine#Specification

File: src/angular-app/languageforge/lexicon/lexicon-app.component.ts [hunk 1]
```diff
@@ -167,29 +167,29 @@ export class LexiconAppController implements angular.IController {
       (document.querySelectorAll('nav.navbar-expand')[1] as HTMLElement).style.backgroundColor = backgroundColorB;
     }
 
-    let offlineMessageId: string;
+    // let offlineMessageId: string;
```
Comment (megahirt) [inline src/angular-app/languageforge/lexicon/lexicon-app.component.ts:170]:
```suggestion
```

File: src/angular-app/languageforge/lexicon/lexicon-app.component.ts [hunk 2]
```diff
@@ -167,29 +167,29 @@ export class LexiconAppController implements angular.IController {
...
       setTitle('Language Forge', '', '');
 
-      if (this.online === false) {
-        this.notice.removeById(offlineMessageId);
-        this.notice.push(this.notice.SUCCESS, 'You are back online!');
-      }
+    //   if (this.online === false) {
+        // this.notice.removeById(offlineMessageId);
+        // this.notice.push(this.notice.SUCCESS, 'You are back online!');
+    //   }
```
Comment (megahirt) [inline src/angular-app/languageforge/lexicon/lexicon-app.component.ts:177]:
```suggestion
```

File: src/angular-app/languageforge/lexicon/lexicon-app.component.ts [hunk 3]
```diff
@@ -167,29 +167,29 @@ export class LexiconAppController implements angular.IController {
...
 
-      this.online = true;
+    //   this.online = true;
```
Comment (megahirt) [inline src/angular-app/languageforge/lexicon/lexicon-app.component.ts:179]:
```suggestion
```

File: src/angular-app/languageforge/lexicon/lexicon-app.component.ts [hunk 4]
```diff
@@ -167,29 +167,29 @@ export class LexiconAppController implements angular.IController {
...
     Offline.on('down', () => {
       setTitle('Language Forge Offline', '#555', '#777');
-      offlineMessageId = this.notice.push(this.notice.ERROR, 'You are offline. Some features are not available', null,
-        true, 5 * 1000);
-      this.online = false;
-      if (!/^\/editor\//.test(this.$location.path())) {
+    //   offlineMessageId = this.notice.push(this.notice.ERROR, 'You are offline. Some features are not available', null,
+        // true, 5 * 1000);
+    //   this.online = false;
+    //   if (!/^\/editor\//.test(this.$location.path())) {
```
Comment (megahirt) [inline src/angular-app/languageforge/lexicon/lexicon-app.component.ts:188]:
```suggestion
```

File: src/angular-app/languageforge/lexicon/lexicon-app.component.ts [hunk 5]
```diff
@@ -167,29 +167,29 @@ export class LexiconAppController implements angular.IController {
...
         // redirect to the editor
-        this.$location.path('/editor');
-        this.notice.push(this.notice.SUCCESS, 'The dictionary editor is available offline.  Settings are not.');
-      }
+        // this.$location.path('/editor');
+        // this.notice.push(this.notice.SUCCESS, 'The dictionary editor is available offline.  Settings are not.');
+    //   }
```
Comment (megahirt) [inline src/angular-app/languageforge/lexicon/lexicon-app.component.ts:192]:
```suggestion
```

**Review by megahirt — APPROVED** [review]
LGTM I would like to go fast on this, and just delete those sections outright, not just comment out.

**Comment by longrunningprocess** [comment]
> LGTM I would like to go fast on this, and just delete those sections outright, not just comment out.

I'm with you, I'd like to get this back in Erika's hands ASAP

**Comment by megahirt** [comment]
TESTED

I observe that no notifications are created when simulating going on/off line.  The header still has the offline text and color change as expected.
