### PR TITLE
Fixed bug where num of entries was being limited to 1,000 on project dashboard

### LINKED ISSUE #1460: Project dashboard limited to max of 1,000 entries
While testing #1416 , I noticed entries are limited to 1,000.

### PR DESCRIPTION
**Pull request by longrunningprocess**
## Description

The number of entries on the project dashboard were being limited to 1,000.

Fixes #1460 

### Type of Change

- Bug fix (non-breaking change which fixes an issue)

## Screenshots

image

## Testing on your branch

- [ ] Visit the project landing page for a project with more than 1,000 entries, e.g., test-rwr-flex, qxh-flex.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the title/description of this PR which will be used as the squashed PR commit message
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works

## qa.languageforge.org testing

Reviewers: add/replace your name below and check the box to sign-off/attest the feature works as expected on qa.languageforge.org

- [ ] Reviewer1 (YYYY-MM-DD HH:MM)
- [ ] Reviewer2 (YYYY-MM-DD HH:MM)

### CODE REVIEW

**Comment by longrunningprocess** [comment]
We should make sure we're ok with the perf hit of this page since we will gather all entries, not just 1,000 at a time.  If the perf is unacceptable, there are plenty of solutions we can consider.

File: next-app/src/routes/projects/[project_code]/meta/+server.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ export async function get({ project_code, cookie }) {
 		{ entries, comments }
 	] = await Promise.all([
 		sf({ name: 'project_read_by_code', args: [ project_code ], cookie }),
-		sf({ name: 'lex_stats', args: [ project_code ], cookie }),
```
Comment (megahirt) [inline next-app/src/routes/projects/[project_code]/meta/+server.ts:9]: just curious, are you still using lex_stats in addition to this?  Or are you only using lex_stats_all now?  If it's no longer used, how about we remove it from PHP.

**Review by megahirt — APPROVED** [review]
LGTM.  This is fixing up stuff related to the activity feed.  My sense is that future data accesses should go directly into Mongo from Svelte.  Perhaps the next thing to do, is to refactor the activity feed in a new paradigm that accesses Mongo directly.  we need to spec this out as a separate task.

I still think there is value in developing an external API with proper JWT and OAuth that could be used by both Language Forge and other apps.

You can resolve the comment yourself so this will merge.

File: next-app/src/routes/projects/[project_code]/meta/+server.ts (hunk 1 above)
Comment (longrunningprocess) [reply next-app/src/routes/projects/[project_code]/meta/+server.ts:9]: I do not use lex_stats but it might be used in the PHP code... if you'd like I'll go digging around to make sure

File: src/Api/Service/Sf.php [hunk 2]
```diff
@@ -558,6 +558,18 @@ public function lex_stats($projectCode)
         throw new UserUnauthorizedException("User $this->userId is not a member of project $projectCode");
 	}
 
+	public function lex_stats_all($projectCode)
+	{
+		$projectModel = ProjectModel::getByProjectCode($projectCode);
+        $user = new UserModel($this->userId);
+
+        if ($user->isMemberOfProject($projectModel->id->asString())) {
+            return LexDbeDto::encode($projectModel->id->asString(), $this->userId, 1);
```
Comment (megahirt) [inline src/Api/Service/Sf.php:567]: So, on later inspection of this code, I'm not really clear how passing 1 into the lastFetchTime achieves more than 1000 entries at a time... maybe it does for you but I actually don't understand how it works.

Comment (megahirt) [reply src/Api/Service/Sf.php:567]: ok, yeah that's definitely a hack.  I want to make a proper stats endpoint to support what you are doing with the dashboard.  That will be a separate card.
