### PR TITLE
Prevent UI updates when there is an unresolved recording in progress

### LINKED ISSUE #1762: bug: UI refreshes often cause audio loss
**Describe the bug**
We have multiple mechanisms in place for refreshing entires/the UI due to various reasons. But there is no safety measure to prevent that from happening while a user is recording or after they have recorded, but haven't yet saved the recording.

**To Reproduce**

1. Start recording
2. Make a change in a text field
3. Wait... 💥

One could argue that a user isn't likely to make a change while they're recording. But there are various things that can trigger the same problem that are much less obvious.

**Expected behavior**
Recording should never be interrupted or lost unless the user explicitly navigates away from the entry/page without resolving it.

### PR DESCRIPTION
**Pull request by myieye**
## Description

See #1762 

## Checklist

- [x] I have labeled my PR with: bug, feature, engineering, security fix or testing
- [x] I have performed a self-review of my own code
- [x] I have reviewed the title & description of this PR which I will use as the squashed PR commit message
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have enabled auto-merge (optional)

## Testing

Testers, use the following instructions against our staging environment. Post your findings as a comment and include any meaningful screenshots, etc.

1) Make various changes to entries while recording, while uploading or anywhere in between and make sure the recording never gets lost.

### CODE REVIEW

File: src/angular-app/languageforge/lexicon/editor/editor.component.ts [hunk 1]
```diff
@@ -369,6 +372,10 @@ export class LexiconEditorController implements angular.IController {
     // entry and is NOT going to a different entry (as is the case with editing another entry.
     let newEntryTempId: string;
 
+    // We might be saving, because the user is navigating away from this entry,
+    // in which case we don't want to lose the upload.
+    await this.recordingStateService.uploading$();
```
Comment (myieye) [inline src/angular-app/languageforge/lexicon/editor/editor.component.ts:377]: @rmunn So, we either: (1) ditch the audio and hope as much gets saved as possible (2) wait for the audio at the risk of the save then never getting run at all or (3) put effort into configuring when we wait.

Comment (myieye) [reply src/angular-app/languageforge/lexicon/editor/editor.component.ts:377]: It's worth mentioning that this is actually just a bonus. The `return` on 1141 is much more significant and effective.

**Review by rmunn — APPROVED** [review]
LGTM. The bit where we block UI updates if an upload is in progress might in theory have a better solution, but implementing that better solution would involve a LOT more work than it's worth considering that nobody will notice the UI updates being blocked in 99.8% of cases. So let's get this merged.
